
###get all subscribers
GET http://localhost:8080/subscribers

###get one subscriber
GET http://localhost:8080/subscribers/63ca2cede18a49f47ba7cbbf

###create one subscriber
POST http://localhost:8080/login
Content-Type: application/json

{
    "name": "Yap",
    "subscribedToChannel": "Web Sim"
}

###delete one subscriber
DELETE http://localhost:8080/subscribers/63c73561a851adf6970d9c16

###delete all subscribers
DELETE http://localhost:8080/subscribers/

###update one subscriber
PATCH http://localhost:8080/subscribers/63c73561a851adf6970d9c16
Content-Type: application/json

###
POST http://localhost:8080/login
Content-Type: application/json

{
    "user": "jiaqijiaqijiaqi",
    "pwd": "$2b$10$INaRVLavz9YbR8AY8en3u.gtw9BLXkwiG6n39ekw1HGlGTHIKVZqy"
}